### ISSUE TITLE
Doc improvment

### ISSUE THREAD

**Issue by sh4bang** [samneirinck/posh-docker#21]
Hi ! I don't know if it is even possible, but... is there any chance to get the tab completion working through "Cmder" terminal with the docker invite added to it ? If yes, it would be helpful to find an install doc here :)

To get docker invite, here is my Cmder config : 
- Go to settings (Win+Alt+P)
- Go to "Startup/Task"
- Add a default task named "docker" : 
-- Task parameters : `/icon "C:\Program Files\Docker Toolbox\docker-quickstart-terminal.ico"` (depending of your own path)
-- Commands : 
`""C:\Program Files\Git\bin\bash.exe" --login -i "C:\Program Files\Docker Toolbox\start.sh" -new_console:d:"C:\Program Files\Docker Toolbox""` (again, depending of your own path)

Edit : 
To enable tab completion on a PowerShell invite from Cmder, you just need to remove the "-NoProfile" command option in the "Startup/Task"

But still impossible to get tab completion on the new "docker" invite, unfortunately.

**Comment by sh4bang** [comment]
A Prerequisites question would be : is there any chance to get tab completion inside the "Docker Quickstart Terminal" ?

**Comment by samneirinck** [comment]
I'm not sure exactly what a 'docker invite' is?

The module should work perfectly fine in Cmder. I'm using conemu (on which Cmder is based on) and it's working without issues, as long as the module has been imported via `Import-Module posh-docker` statement.

If I have a look at the quickstart command you have for cmder, it launches bash. Since this is tab completion for powershell, it won't work and you'll have to take a look at the [official documentation](https://docs.docker.com/compose/completion/#bash) for bash completion.

**Comment by sh4bang** [comment]
By 'docker invite' I tried to say 'Docker Quickstart Terminal via Cmder (or ConEmu)'.

I confirm the module works perfectly with Cmder. You right about the bash : my wish about having tab completing through "Docker Quickstart Terminal" is hopeless :D 

Thanks for your time, and gratz for that amazing plugin ! You can close that ticket for sure.
